<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="HEArc.RSVP.RSVP">
    <abbreviation>
        <text>RSVP</text>
     </abbreviation>
     <description>Handles RSVP protocol messages</description>
     <mil-modules></mil-modules>
     <assembly name="HEArc.RSVP.dll"/>
     <assembly type="UI" name="HEArc.RSVPUI.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>