<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="HEArc_SqlServerPackage.SqlServer">
    <abbreviation>
        <text>SQL</text>
     </abbreviation>
     <description>Client for Microsoft SQL server.</description>
     <mil-modules></mil-modules>
     <assembly name="HEArc_SqlServerPackage.dll"/>
     <assembly type="UI" name="HEArc_SqlServerUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>